version: "3"
services:
  frontend:
    restart: on-failure
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ${PWD}/frontend:/usr/share/nginx/html:ro
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    restart: on-failure
    build: ./backend
    ports:
      - 3030:3030
