version: "3"
services:
  frontend:
    build: ./frontend
    image: ${REGISTRY}/file-uploader_frontend:${VERSION}
    restart: on-failure
    ports:
      - 8080:80
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  backend2:
    build: ./backend2
    image: ${REGISTRY}/file-uploader_backend2:${VERSION}
    restart: on-failure
    ports:
      - 3030:3030
