version: "3"
services:
  frontend:
    build: ./frontend
    image: ${REGISTRY}/file-uploader_frontend:${VERSION}
    restart: on-failure
    ports:
      - 8080:80

  backend:
    build: ./backend
    image: ${REGISTRY}/file-uploader_backend:${VERSION}
    restart: on-failure
    ports:
      - 3030:3030
