apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: file-uploader.frontend.service
spec:
  selector:
    app: file-uploader.frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
